# Generated by Django 3.0.8 on 2020-07-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='user',
        ),
    ]
